import type { RuntimeSensor } from './models'

function generateDailyRuntime(days: number, avgHours: number, variance: number) {
  const data = []
  const now = new Date('2026-02-26')
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    const dayOfWeek = d.getDay()
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6
    const base = isWeekend ? avgHours * 0.4 : avgHours
    const hours = Math.max(0, Math.min(24, base + (Math.random() - 0.5) * variance * 2))
    const cycles = Math.round(hours * (3 + Math.random() * 2))
    data.push({
      date: d.toISOString().split('T')[0],
      hours: Math.round(hours * 10) / 10,
      cycles,
    })
  }
  return data
}

export const runtimeSensors: RuntimeSensor[] = [
  {
    id: 'RS-001',
    name: 'AirComp 115PSI | BL1 - 150 AMP',
    assetId: 'A-205',
    assetName: 'Pump P-401',
    locationName: 'Main Office',
    gatewayId: 'GW-001',
    gatewayName: 'FC - 168CMF',
    type: 'UpKeep Current',
    status: 'connected',
    totalHours: 487.2,
    previousPeriodHours: 462.8,
    avgDailyHours: 16.2,
    peakDay: { date: '2026-02-19', hours: 21.3 },
    uptimePercent: 94.6,
    dailyRuntime: generateDailyRuntime(30, 16.2, 4),
    meter: {
      currentReading: 12847,
      unit: 'hours',
      lastResetDate: '2025-08-15',
      totalCycles: 48920,
      avgCyclesPerDay: 78,
      nextServiceAt: 15000,
    },
    meterName: '#AirComp Runtime | BL1 - EC',
    meterSyncEnabled: true,
    runtimeThreshold: 15,
    workOrders: [
      { id: 'WO-2044', title: 'Vibration anomaly detected', status: 'in_progress', createdAt: '2026-02-22', urgency: 'high' },
      { id: 'WO-2031', title: 'Bearing lubrication PM', status: 'completed', createdAt: '2026-02-10', urgency: 'medium' },
    ],
    lastReading: '5 min ago',
    insights: [
      'Runtime increased 5.3% compared to previous 30-day period',
      'Peak usage consistently on Wednesdays — consider load balancing',
      'Approaching next service milestone at 15,000 hours (currently 12,847)',
    ],
  },
  {
    id: 'RS-002',
    name: 'Cool Storage | EC - HMD',
    assetId: 'A-101',
    assetName: 'HVAC Unit #12',
    locationName: 'Warehouse B01',
    gatewayId: 'GW-001',
    gatewayName: 'FC - 168CMF',
    type: 'UpKeep Humidity',
    status: 'connected',
    totalHours: 692.4,
    previousPeriodHours: 710.1,
    avgDailyHours: 23.1,
    peakDay: { date: '2026-02-14', hours: 24.0 },
    uptimePercent: 99.2,
    dailyRuntime: generateDailyRuntime(30, 23.1, 1.5),
    meter: {
      currentReading: 34210,
      unit: 'hours',
      lastResetDate: '2024-03-01',
      totalCycles: 102630,
      avgCyclesPerDay: 142,
      nextServiceAt: 35000,
    },
    meterName: '#CoolStorage Runtime | EC - HMD',
    meterSyncEnabled: true,
    runtimeThreshold: 10,
    workOrders: [
      { id: 'WO-2041', title: 'HVAC compressor failure', status: 'open', createdAt: '2026-02-24', urgency: 'critical' },
    ],
    lastReading: '2 min ago',
    insights: [
      'Near-continuous operation (99.2% uptime) — asset running almost 24/7',
      'Runtime decreased 2.5% vs previous period — compressor issues may be causing intermittent shutdowns',
      'Approaching 35,000 hour service milestone — only 790 hours remaining',
    ],
  },
  {
    id: 'RS-003',
    name: 'TurboAir 120PSI | BL2 - EC',
    assetId: 'A-302',
    assetName: 'Conveyor #3',
    locationName: 'Plant Floor - Line 3',
    gatewayId: 'GW-002',
    gatewayName: 'FC - 169CMF',
    type: 'UpKeep Current',
    status: 'connected',
    totalHours: 312.6,
    previousPeriodHours: 318.2,
    avgDailyHours: 10.4,
    peakDay: { date: '2026-02-17', hours: 14.8 },
    uptimePercent: 87.3,
    dailyRuntime: generateDailyRuntime(30, 10.4, 3),
    meter: {
      currentReading: 8456,
      unit: 'hours',
      lastResetDate: '2025-06-10',
      totalCycles: 33824,
      avgCyclesPerDay: 54,
      nextServiceAt: 10000,
    },
    meterName: '#TurboAir Runtime | BL2 - EC',
    meterSyncEnabled: false,
    runtimeThreshold: 8,
    workOrders: [
      { id: 'WO-2038', title: 'Conveyor belt misalignment', status: 'in_progress', createdAt: '2026-02-20', urgency: 'high' },
      { id: 'WO-2029', title: 'Motor temperature check', status: 'completed', createdAt: '2026-02-05', urgency: 'medium' },
      { id: 'WO-2022', title: 'Belt replacement', status: 'completed', createdAt: '2026-01-15', urgency: 'low' },
    ],
    lastReading: '12 min ago',
    insights: [
      'Consistent daily pattern — 2-shift operation detected',
      'Weekend runtime is 60% lower than weekdays — normal production schedule',
      '1,544 hours until next service interval',
    ],
  },
  {
    id: 'RS-004',
    name: 'MaxAir 120PSI - ALA 1223',
    assetId: 'A-410',
    assetName: 'Cooling Tower #2',
    locationName: '2nd Floor - Mechanical',
    gatewayId: 'GW-002',
    gatewayName: 'FC - 169CMF',
    type: 'UpKeep Temperature',
    status: 'warning',
    totalHours: 580.1,
    previousPeriodHours: 612.0,
    avgDailyHours: 19.3,
    peakDay: { date: '2026-02-12', hours: 23.1 },
    uptimePercent: 91.8,
    dailyRuntime: generateDailyRuntime(30, 19.3, 3.5),
    runtimeThreshold: 12,
    workOrders: [
      { id: 'WO-2046', title: 'Cooling tower fan bearing replacement', status: 'open', createdAt: '2026-02-23', urgency: 'medium' },
    ],
    lastReading: '8 min ago',
    insights: [
      'Runtime dropped 5.2% vs last period — flow rate decline may be causing efficiency loss',
      'Vibration levels trending up — correlates with reduced runtime efficiency',
      '2,870 hours to next major service at 25,000 hours',
    ],
  },
  {
    id: 'RS-005',
    name: 'PowerAir 120PSI | BL3',
    assetId: 'A-503',
    assetName: 'Generator #1',
    locationName: 'Warehouse East - Utility',
    gatewayId: 'GW-003',
    gatewayName: 'FC - 170CMF',
    type: 'UpKeep Current',
    status: 'connected',
    totalHours: 124.8,
    previousPeriodHours: 118.5,
    avgDailyHours: 4.2,
    peakDay: { date: '2026-02-26', hours: 18.2 },
    uptimePercent: 100,
    dailyRuntime: generateDailyRuntime(30, 4.2, 6),
    workOrders: [
      { id: 'WO-2039', title: 'Generator oil change PM', status: 'open', createdAt: '2026-02-24', urgency: 'medium' },
    ],
    lastReading: '3 min ago',
    insights: [
      'Standby generator — low average runtime but spikes during outages',
      'Feb 26 peak of 18.2h coincides with power outage event',
      'Oil change due — 320 hours until 6,000 hour service mark',
    ],
  },
  {
    id: 'RS-006',
    name: 'SuperAir 120PSI | BL4',
    assetId: 'A-604',
    assetName: 'Boiler #3',
    locationName: 'Main Office - Basement',
    gatewayId: 'GW-001',
    gatewayName: 'FC - 168CMF',
    type: 'UpKeep Temperature',
    status: 'disconnected',
    totalHours: 0,
    previousPeriodHours: 548.2,
    avgDailyHours: 0,
    peakDay: { date: '2026-02-01', hours: 22.4 },
    uptimePercent: 0,
    dailyRuntime: generateDailyRuntime(30, 0, 0).map((d, i) => ({
      ...d,
      hours: i < 15 ? Math.round((18 + Math.random() * 4) * 10) / 10 : 0,
      cycles: i < 15 ? Math.round((18 + Math.random() * 4) * 5) : 0,
    })),
    workOrders: [
      { id: 'WO-2050', title: 'Boiler offline — no sensor data', status: 'open', createdAt: '2026-02-12', urgency: 'critical' },
    ],
    lastReading: '14 days ago',
    insights: [
      'Sensor disconnected since Feb 12 — no runtime data available',
      'Was running ~18-22 hours/day before disconnection',
      'Critical: asset may be running without monitoring',
    ],
  },
  {
    id: 'RS-007',
    name: 'EliteAir 120PSI | BL5',
    assetId: 'A-715',
    assetName: 'Chiller Unit #1',
    locationName: 'Main Office - Rooftop',
    gatewayId: 'GW-003',
    gatewayName: 'FC - 170CMF',
    type: 'UpKeep Current',
    status: 'connected',
    totalHours: 445.3,
    previousPeriodHours: 430.1,
    avgDailyHours: 14.8,
    peakDay: { date: '2026-02-20', hours: 19.5 },
    uptimePercent: 96.1,
    dailyRuntime: generateDailyRuntime(30, 14.8, 3),
    meter: {
      currentReading: 9870,
      unit: 'hours',
      lastResetDate: '2025-04-01',
      totalCycles: 39480,
      avgCyclesPerDay: 65,
      nextServiceAt: 10000,
    },
    meterName: '#EliteAir Runtime | BL5 - EC',
    meterSyncEnabled: true,
    runtimeThreshold: 10,
    workOrders: [],
    lastReading: '1 min ago',
    insights: [
      'Healthy operation — runtime stable and within expected range',
      'Approaching 10,000 hour service milestone (130 hours away)',
      'Efficiency remains consistent — no anomalies detected',
    ],
  },
  {
    id: 'RS-008',
    name: 'CompAir 200PSI | BL6',
    assetId: 'A-820',
    assetName: 'Air Compressor #4',
    locationName: 'Plant Floor - Zone A',
    gatewayId: 'GW-002',
    gatewayName: 'FC - 169CMF',
    type: 'UpKeep Vibration',
    status: 'connected',
    totalHours: 398.7,
    previousPeriodHours: 385.2,
    avgDailyHours: 13.3,
    peakDay: { date: '2026-02-18', hours: 17.6 },
    uptimePercent: 92.4,
    dailyRuntime: generateDailyRuntime(30, 13.3, 3.5),
    meter: {
      currentReading: 15430,
      unit: 'hours',
      lastResetDate: '2024-09-01',
      totalCycles: 61720,
      avgCyclesPerDay: 82,
      nextServiceAt: 20000,
    },
    meterName: '#CompAir Runtime | BL6 - EC',
    meterSyncEnabled: true,
    runtimeThreshold: 12,
    workOrders: [
      { id: 'WO-2047', title: 'Vibration analysis review', status: 'completed', createdAt: '2026-02-15', urgency: 'low' },
    ],
    lastReading: '6 min ago',
    insights: [
      'Runtime increased 3.5% vs previous period — higher production demand',
      'Vibration sensor showing stable readings — no concerns',
      '4,570 hours until next major service interval',
    ],
  },
]
